export type Category = "Research" | "Apps" | "School projects" | "Humanitarian";

export type Project = {
  slug: string;
  title: string;
  description: string;
  stack: string[];
  category: Category;
  thumbnail?: string;
  links?: { demo?: string; repo?: string; pdf?: string };
};

/**
 * TODO(cedric): every entry below marked TODO needs real content.
 * Card count follows the sketch: 3 Research, 6 Apps, 3 Humanitarian.
 */
export const projects: Project[] = [
  // ---- Research -----------------------------------------------------------
  {
    slug: "curriculum-rag-thesis",
    title:
      "Curriculum-Grounded Retrieval-Augmented Generation for Terminale C Mathematics Self-Tutoring in Côte d'Ivoire",
    description:
      "MSc thesis (HEC Paris · École Polytechnique, 2026). A RAG tutor grounded in the Ivorian CIAM curriculum: a 722-segment annotated corpus, a four-variant retrieval stack, and a novel pedagogical retriever enforcing a theory-plus-worked-example mix.",
    stack: ["RAG", "LLM", "BM25", "Multilingual-E5", "Python"],
    category: "Research",
    thumbnail: "/images/curriculum-rag-thesis.jpg",
    links: { pdf: "/docs/hec-msc-thesis-curriculum-rag.pdf" },
  },
  {
    slug: "flood-waste-prediction",
    title:
      "A Regression Model for Flood Waste Prediction in Abidjan, Côte d'Ivoire",
    description:
      "MSc thesis (Tokyo Institute of Technology, 2024). A regression model estimating the solid waste generated by urban flooding in Abidjan, to support municipal response planning.",
    stack: ["Regression", "Python", "Geospatial data"],
    category: "Research",
    thumbnail: "/images/flood-project.jpg",
    links: {
      pdf: "/docs/tokyotech-msc-thesis-flood-waste-prediction.pdf",
      repo: "https://github.com/cedrickirek/gen-ai-flood-scenario-analysis",
    },
  },

  // ---- Apps ---------------------------------------------------------------
  {
    slug: "tutorly",
    title: "Tutorly",
    description:
      "A hybrid human–AI tutoring marketplace pairing each client with a human tutor and a personalised LLM assistant for 24/7 support. Started at the HEC Paris Start-up Launchpad.",
    stack: ["LLM", "Marketplace", "EdTech"],
    category: "Apps",
    thumbnail: "/images/tutorly.jpg",
  },
  {
    slug: "basketball-shooting-analyzer",
    title: "Yes I Can Shoot — Basketball Form Analyzer",
    description:
      "Analyses basketball shooting form by detecting body pose and calculating the release angle at the elbow, giving instant visual feedback and recommendations.",
    stack: ["Python", "MediaPipe", "OpenCV", "Gradio"],
    category: "Apps",
    thumbnail: "/images/basketball-project.jpg",
    links: {
      repo: "https://github.com/cedrickirek/yes-I-can-shoot_basketball-project",
    },
  },
  {
    slug: "youtube-transcriber",
    title: "YouTube Video Transcriber & Note Generator",
    description:
      "Transcribes and summarises YouTube videos into digestible notes, built because too many hours were disappearing into the feed.",
    stack: ["Python", "Streamlit", "OpenAI", "NLP"],
    category: "Apps",
    thumbnail: "/images/youtube-videos_summary.png",
    links: { repo: "https://github.com/cedrickirek/transcribing_videos" },
  },

  // ---- School projects ----------------------------------------------------
  // TODO(cedric): add your data science coursework projects here, following
  // the shape above: title, one-line description, stack, and links.

  // ---- Humanitarian -------------------------------------------------------
  {
    slug: "kits-scolaires",
    title: "Kits Scolaires — donation transparency app",
    description:
      "A donation platform for an Ivorian association funding school kits. Donors fund campaigns rather than individual children, and every purchase and delivery is published with receipts and consent-gated photos — the transparency is the product's whole argument.",
    stack: ["Next.js", "TypeScript", "Supabase", "PostgreSQL", "PayDunya"],
    category: "Humanitarian",
    thumbnail: "/images/kits-scolaires.jpg",
    // Repo is private; the live deployment is the public artefact.
    links: { demo: "https://donation-app-wine.vercel.app/" },
  },
];

export const categories: Category[] = [
  "Research",
  "Apps",
  "School projects",
  "Humanitarian",
];

export const byCategory = (category: Category) =>
  projects.filter((p) => p.category === category);

/**
 * Slugs of the first few cards that actually carry a thumbnail, in page order.
 * These get `priority` so the LCP image is not lazy-loaded — cards without a
 * thumbnail are skipped, since they render no image to prioritise.
 */
export const prioritySlugs = new Set(
  projects
    .filter((p) => p.thumbnail)
    .slice(0, 3)
    .map((p) => p.slug),
);
