export type Category = "Research" | "Apps" | "Humanitarian";

export type Project = {
  slug: string;
  title: string;
  description: string;
  stack: string[];
  category: Category;
  /** Larger card. Lead each category with its strongest one or two entries. */
  featured?: boolean;
  thumbnail?: string;
  links?: { demo?: string; repo?: string; pdf?: string };
};

/**
 * TODO(cedric): every entry below marked TODO needs real content.
 * Card count follows the sketch: 3 Research, 6 Apps, 3 Humanitarian.
 */
export const projects: Project[] = [
  // ---- Research -----------------------------------------------------------
  {
    slug: "curriculum-rag-thesis",
    title:
      "Curriculum-Grounded Retrieval-Augmented Generation for Terminale C Mathematics Self-Tutoring in Côte d'Ivoire",
    description:
      "MSc thesis (HEC Paris · École Polytechnique, 2026). A RAG tutor grounded in the Ivorian CIAM curriculum: a 722-segment annotated corpus, a four-variant retrieval stack, and a novel pedagogical retriever enforcing a theory-plus-worked-example mix.",
    stack: ["RAG", "LLM", "BM25", "Multilingual-E5", "Python"],
    category: "Research",
    featured: true,
    links: { pdf: "/docs/hec-msc-thesis-curriculum-rag.pdf" },
  },
  {
    slug: "flood-waste-prediction",
    title: "A Regression Model for Flood Waste Prediction in Abidjan, Côte d'Ivoire",
    description:
      "MSc thesis (Tokyo Institute of Technology, 2024). A regression model estimating the solid waste generated by urban flooding in Abidjan, to support municipal response planning.",
    stack: ["Regression", "Python", "Geospatial data"],
    category: "Research",
    featured: true,
    thumbnail: "/images/flood-project.jpg",
    links: {
      pdf: "/docs/tokyotech-msc-thesis-flood-waste-prediction.pdf",
      repo: "https://github.com/cedrickirek/gen-ai-flood-scenario-analysis",
    },
  },
  {
    slug: "research-3",
    title: "TODO(cedric): third research project",
    description: "TODO(cedric): one-line description.",
    stack: ["TODO"],
    category: "Research",
  },

  // ---- Apps ---------------------------------------------------------------
  {
    slug: "tutorly",
    title: "Tutorly",
    description:
      "A hybrid human–AI tutoring marketplace pairing each client with a human tutor and a personalised LLM assistant for 24/7 support. Started at the HEC Paris Start-up Launchpad.",
    stack: ["LLM", "Marketplace", "EdTech"],
    category: "Apps",
    featured: true,
  },
  {
    slug: "basketball-shooting-analyzer",
    title: "Yes I Can Shoot — Basketball Form Analyzer",
    description:
      "Analyses basketball shooting form by detecting body pose and calculating the release angle at the elbow, giving instant visual feedback and recommendations.",
    stack: ["Python", "MediaPipe", "OpenCV", "Gradio"],
    category: "Apps",
    thumbnail: "/images/basketball-project.jpg",
    links: {
      repo: "https://github.com/cedrickirek/yes-I-can-shoot_basketball-project",
    },
  },
  {
    slug: "youtube-transcriber",
    title: "YouTube Video Transcriber & Note Generator",
    description:
      "Transcribes and summarises YouTube videos into digestible notes, built because too many hours were disappearing into the feed.",
    stack: ["Python", "Streamlit", "OpenAI", "NLP"],
    category: "Apps",
    thumbnail: "/images/youtube-videos_summary.png",
    links: { repo: "https://github.com/cedrickirek/transcribing_videos" },
  },
  {
    slug: "app-4",
    title: "TODO(cedric): fourth app",
    description: "TODO(cedric): one-line description.",
    stack: ["TODO"],
    category: "Apps",
  },
  {
    slug: "app-5",
    title: "TODO(cedric): fifth app",
    description: "TODO(cedric): one-line description.",
    stack: ["TODO"],
    category: "Apps",
  },
  {
    slug: "app-6",
    title: "TODO(cedric): sixth app",
    description: "TODO(cedric): one-line description.",
    stack: ["TODO"],
    category: "Apps",
  },

  // ---- Humanitarian -------------------------------------------------------
  {
    slug: "humanitarian-1",
    title: "TODO(cedric): first humanitarian project",
    description: "TODO(cedric): one-line description.",
    stack: ["TODO"],
    category: "Humanitarian",
    featured: true,
  },
  {
    slug: "humanitarian-2",
    title: "TODO(cedric): second humanitarian project",
    description: "TODO(cedric): one-line description.",
    stack: ["TODO"],
    category: "Humanitarian",
  },
  {
    slug: "humanitarian-3",
    title: "TODO(cedric): third humanitarian project",
    description: "TODO(cedric): one-line description.",
    stack: ["TODO"],
    category: "Humanitarian",
  },
];

export const categories: Category[] = ["Research", "Apps", "Humanitarian"];

export const byCategory = (category: Category) =>
  projects.filter((p) => p.category === category);

/**
 * Slugs of the first few cards that actually carry a thumbnail, in page order.
 * These get `priority` so the LCP image is not lazy-loaded — cards without a
 * thumbnail are skipped, since they render no image to prioritise.
 */
export const prioritySlugs = new Set(
  projects.filter((p) => p.thumbnail).slice(0, 3).map((p) => p.slug),
);
